/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-03-17 13:12:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registeruser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1647512434000L));
    _jspx_dependants.put("/alertMessage.jsp", Long.valueOf(1647512434000L));
    _jspx_dependants.put("/css/style.css", Long.valueOf(1647512434000L));
    _jspx_dependants.put("/css/registrationStyle.css", Long.valueOf(1647512434000L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1647512434000L));
    _jspx_dependants.put("/js/registrationScript.js", Long.valueOf(1647512434000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Sign Up | Login</title>\n");
      out.write("\n");
      out.write("<!-- fontawesome icons -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://pro.fontawesome.com/releases/v5.10.0/css/all.css\"\n");
      out.write("	integrity=\"sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p\"\n");
      out.write("	crossorigin=\"anonymous\" />\n");
      out.write("\n");
      out.write("<!-- Custom CSS -->\n");
      out.write("<style>");
      out.write("@charset \"ISO-8859-1\";\n");
      out.write("\n");
      out.write("#icon {\n");
      out.write("	color: #F012BE;\n");
      out.write("	text-shadow: 3px 3px 5px #FF0000, 0 3px 5px #0000FF;\n");
      out.write("	font-size: 45px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".nav-link {\n");
      out.write("	font-size: 20px;\n");
      out.write("	margin: 8px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bodyImage {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 500px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#footer {\n");
      out.write("	position: fixed;\n");
      out.write("	bottom: 0;\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".glyphicon {\n");
      out.write("	margin-bottom: 10px;\n");
      out.write("	margin-right: 10px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("small {\n");
      out.write("	display: block;\n");
      out.write("	line-height: 1.428571429;\n");
      out.write("	color: #999;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".bottom {\n");
      out.write("	padding: 0 20px;\n");
      out.write("	margin-bottom: 17px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn {\n");
      out.write("	border-radius: 50%;\n");
      out.write("	width: 32px;\n");
      out.write("	height: 32px;\n");
      out.write("	line-height: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn5 {\n");
      out.write("	background-color: #4CAF50;\n");
      out.write("	border: none;\n");
      out.write("	color: white;\n");
      out.write("	padding: 16px 32px;\n");
      out.write("	text-align: center;\n");
      out.write("	text-decoration: none;\n");
      out.write("	display: inline-block;\n");
      out.write("	font-size: 16px;\n");
      out.write("	margin: 4px 2px;\n");
      out.write("	transition-duration: 0.4s;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn6 {\n");
      out.write("	background-color: white;\n");
      out.write("	color: black;\n");
      out.write("	border: 2px solid #4CAF50;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn6:hover {\n");
      out.write("	background-color: #4CAF50;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn7 {\n");
      out.write("	background-color: white;\n");
      out.write("	color: black;\n");
      out.write("	border: 2px solid #4CAF50;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn7:hover {\n");
      out.write("	background-color: #4CAF50;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn8 {\n");
      out.write("	background-color: white;\n");
      out.write("	color: black;\n");
      out.write("	border: 2px solid #008CBA;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn8:hover {\n");
      out.write("	background-color: #008CBA;\n");
      out.write("	color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".panel-title {\n");
      out.write("	display: inline;\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".checkbox.pull-right {\n");
      out.write("	margin: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".pl-ziro {\n");
      out.write("	padding-left: 0px;\n");
      out.write("}");
      out.write("</style>\n");
      out.write("<style>");
      out.write("@charset \"ISO-8859-1\";\n");
      out.write("\n");
      out.write("@import url('https://fonts.googleapis.com/css?family=Mukta');\n");
      out.write("\n");
      out.write("body {\n");
      out.write("	font-family: 'Mukta', sans-serif;\n");
      out.write("	height: 100vh;\n");
      out.write("	min-height: 550px;\n");
      out.write("	background-repeat: no-repeat;\n");
      out.write("	background-size: cover;\n");
      out.write("	background-position: center;\n");
      out.write("	position: relative;\n");
      out.write("	overflow-y: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: #444444;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-reg-panel {\n");
      out.write("	margin-top: 70px;\n");
      out.write("	position: relative;\n");
      out.write("	top: 45%;\n");
      out.write("	transform: translateY(-50%);\n");
      out.write("	text-align: center;\n");
      out.write("	width: 70%;\n");
      out.write("	right: 0;\n");
      out.write("	left: 0;\n");
      out.write("	margin: auto;\n");
      out.write("	height: 380px;\n");
      out.write("	background-color: rgba(236, 48, 20, 0.9);\n");
      out.write("}\n");
      out.write("\n");
      out.write(".white-panel {\n");
      out.write("	background-color: rgba(255, 255, 255, 1);\n");
      out.write("	height: 500px;\n");
      out.write("	position: absolute;\n");
      out.write("	top: -50px;\n");
      out.write("	width: 50%;\n");
      out.write("	right: calc(50% - 50px);\n");
      out.write("	transition: .3s ease-in-out;\n");
      out.write("	z-index: 0;\n");
      out.write("	box-shadow: 0 0 15px 9px #00000096;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-reg-panel input[type=\"radio\"] {\n");
      out.write("	position: relative;\n");
      out.write("	display: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-reg-panel {\n");
      out.write("	color: #B8B8B8;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-reg-panel #label-login, .login-reg-panel #label-register {\n");
      out.write("	border: 1px solid #9E9E9E;\n");
      out.write("	padding: 5px 5px;\n");
      out.write("	width: 150px;\n");
      out.write("	display: block;\n");
      out.write("	text-align: center;\n");
      out.write("	border-radius: 10px;\n");
      out.write("	cursor: pointer;\n");
      out.write("	font-weight: 600;\n");
      out.write("	font-size: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-info-box {\n");
      out.write("	width: 30%;\n");
      out.write("	padding: 0 50px;\n");
      out.write("	top: 20%;\n");
      out.write("	left: 0;\n");
      out.write("	position: absolute;\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".register-info-box {\n");
      out.write("	width: 30%;\n");
      out.write("	padding: 0 50px;\n");
      out.write("	top: 20%;\n");
      out.write("	right: 0;\n");
      out.write("	position: absolute;\n");
      out.write("	text-align: left;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".right-log {\n");
      out.write("	right: 50px !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-show, .register-show {\n");
      out.write("	z-index: 1;\n");
      out.write("	display: none;\n");
      out.write("	opacity: 0;\n");
      out.write("	transition: 0.3s ease-in-out;\n");
      out.write("	color: #242424;\n");
      out.write("	text-align: left;\n");
      out.write("	padding: 50px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".show-log-panel {\n");
      out.write("	display: block;\n");
      out.write("	opacity: 0.9;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-show input[type=\"email\"], .login-show input[type=\"password\"] {\n");
      out.write("	width: 100%;\n");
      out.write("	display: block;\n");
      out.write("	margin: 20px 0;\n");
      out.write("	padding: 15px;\n");
      out.write("	border: 1px solid #b5b5b5;\n");
      out.write("	outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-show input[type=\"submit\"] {\n");
      out.write("	max-width: 150px;\n");
      out.write("	width: 100%;\n");
      out.write("	background: #444444;\n");
      out.write("	color: #f9f9f9;\n");
      out.write("	border: none;\n");
      out.write("	padding: 10px;\n");
      out.write("	border-radius: 2px;\n");
      out.write("	float: right;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".login-show a {\n");
      out.write("	display: inline-block;\n");
      out.write("	padding: 10px 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".register-show input[type=\"text\"], .register-show input[type=\"email\"], .register-show input[type=\"number\"],\n");
      out.write("	.register-show input[type=\"password\"] {\n");
      out.write("	width: 100%;\n");
      out.write("	display: block;\n");
      out.write("	margin: 5px 0;\n");
      out.write("	padding: 5px;\n");
      out.write("	border: 1px solid #b5b5b5;\n");
      out.write("	outline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".register-show input[type=\"submit\"] {\n");
      out.write("	max-width: 150px;\n");
      out.write("	width: 100%;\n");
      out.write("	background: #444444;\n");
      out.write("	color: #f9f9f9;\n");
      out.write("	border: none;\n");
      out.write("	padding: 10px;\n");
      out.write("	border-radius: 2px;\n");
      out.write("	float: right;\n");
      out.write("	cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".credit {\n");
      out.write("	position: absolute;\n");
      out.write("	bottom: 10px;\n");
      out.write("	left: 10px;\n");
      out.write("	color: #3B3B25;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("	font-family: Arial, sans-serif;\n");
      out.write("	text-transform: uppercase;\n");
      out.write("	font-size: 12px;\n");
      out.write("	font-weight: bold;\n");
      out.write("	letter-spacing: 1px;\n");
      out.write("	z-index: 99;\n");
      out.write("}\n");
      out.write("\n");
      out.write("a {\n");
      out.write("	text-decoration: none;\n");
      out.write("	color: #2c7715;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#footer {\n");
      out.write("	position: relative;\n");
      out.write("	top: 151px;\n");
      out.write("	bottom: 0;\n");
      out.write("	width: 100%;\n");
      out.write("}");
      out.write("</style>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\n");
      out.write("  \n");
      out.write("</head>\n");
      out.write("<body style=\"background-image: url(https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2017/02/airplane-flight-sunset.jpg?itok=8iUtkHU-);\">\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- header section -->\n");
      out.write("	<div id=\"header\">\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("	<div class=\"container-fluid\">\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("			data-bs-target=\"#navbarTogglerDemo03\"\n");
      out.write("			aria-controls=\"navbarTogglerDemo03\" aria-expanded=\"false\"\n");
      out.write("			aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("		<a class=\"navbar-brand\" href=\"/AirlineReservationSystem\"><i\n");
      out.write("			class=\"fas fa-plane-departure\" id=\"icon\"></i></a>\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarTogglerDemo03\">\n");
      out.write("			<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("					aria-current=\"page\" href=\"index.jsp\"><i\n");
      out.write("						class=\"fas fa-home text-primary\"></i>&nbsp;Home</a></li>\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-white\" href=\"flight\"><i\n");
      out.write("						class=\"fas fa-plane text-info\"></i>&nbsp;Flight</a></li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-white\"\n");
      out.write("					href=\"registeruser.jsp\"><i class=\"fas fa-sign-in-alt\"\n");
      out.write("						style=\"color: #70ffff;\"></i>&nbsp;Login</a></li>\n");
      out.write("\n");
      out.write("				");

				String message = (String) session.getAttribute("username");

				if (message != null) {
					// show the alert msg
				
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link text-white\"\n");
      out.write("					href=\"/AirlineReservationSystem/logout\"><i class=\"fas fa-sign-out-alt\"\n");
      out.write("						style=\"color: #70ffff;\"></i>&nbsp;Logout</a></li>\n");
      out.write("\n");
      out.write("				");

				}
				
      out.write("\n");
      out.write("\n");
      out.write("			</ul>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Alert box - message -->\n");
      out.write("	<div>\n");
      out.write("		");
      out.write('\n');
      out.write('\n');
      out.write('\n');

String msg = (String) session.getAttribute("alertMsg");

if (msg != null) {
	// show the alert msg

      out.write("\n");
      out.write("\n");
      out.write("<svg xmlns=\"http://www.w3.org/2000/svg\" style=\"display: none;\">\n");
      out.write("  <symbol id=\"check-circle-fill\" fill=\"currentColor\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path\n");
      out.write("		d=\"M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z\" />\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"info-fill\" fill=\"currentColor\" viewBox=\"0 0 16 16\">\n");
      out.write("    <path\n");
      out.write("		d=\"M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z\" />\n");
      out.write("  </symbol>\n");
      out.write("  <symbol id=\"exclamation-triangle-fill\" fill=\"currentColor\"\n");
      out.write("		viewBox=\"0 0 16 16\">\n");
      out.write("    <path\n");
      out.write("		d=\"M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z\" />\n");
      out.write("  </symbol>\n");
      out.write("</svg>\n");
      out.write("\n");
      out.write("<div class=\"alert alert-success d-flex align-items-center alert-dismissible fade show\"\n");
      out.write("	role=\"alert\">\n");
      out.write("	<svg class=\"bi flex-shrink-0 me-2\" width=\"24\" height=\"24\" role=\"img\"\n");
      out.write("		aria-label=\"Info:\">\n");
      out.write("		<use xlink:href=\"#info-fill\" /></svg>\n");
      out.write("	<strong>&nbsp;&nbsp;");
      out.print(msg);
      out.write("</strong>\n");
      out.write("	<button type=\"button\" class=\"close\" data-dismiss=\"alert\"\n");
      out.write("		aria-label=\"Close\">\n");
      out.write("		<span aria-hidden=\"true\">&times;</span>\n");
      out.write("	</button>\n");
      out.write("</div>\n");
      out.write("\n");

//removing the session
//It sets the value of the session as null
session.removeAttribute("alertMsg");
}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("	<!-- Sign Up and Login Page -->\n");
      out.write("	<div class=\"login-reg-panel\">\n");
      out.write("		<div class=\"login-info-box\">\n");
      out.write("			<h2 class=\"text-white\">Have an account?</h2>\n");
      out.write("			<label id=\"label-register\" for=\"log-reg-show\" class=\"text-white\">Login</label>\n");
      out.write("			<input type=\"radio\" name=\"active-log-panel\" id=\"log-reg-show\"\n");
      out.write("				checked=\"checked\">\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"register-info-box\">\n");
      out.write("			<h2 class=\"text-white\">Don't have an account?</h2>\n");
      out.write("			<label id=\"label-login\" for=\"log-login-show\" class=\"text-white\">Sign\n");
      out.write("				Up</label> <input type=\"radio\" name=\"active-log-panel\" id=\"log-login-show\">\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div class=\"white-panel\">\n");
      out.write("			<div class=\"login-show\">\n");
      out.write("				<h2>LogIn</h2>\n");
      out.write("				<form action=\"");
      out.print(request.getContextPath());
      out.write("/Login\" method=\"post\">\n");
      out.write("					<input type=\"email\" name=\"emailid\" placeholder=\"Emailid\"> \n");
      out.write("					<input type=\"password\" name=\"password\" placeholder=\"Password\"> \n");
      out.write("					<input type=\"submit\" value=\"Login\">\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"register-show\">\n");
      out.write("				<h2>Create an Account</h2>\n");
      out.write("                <form action=\"");
      out.print( request.getContextPath() );
      out.write("/register\" method=\"post\">\n");
      out.write("					<input type=\"text\" name=\"fname\" placeholder=\"Firstname\">\n");
      out.write("					<input type=\"text\" name=\"lname\" placeholder=\"Lastname\">\n");
      out.write("					<input type=\"text\" name=\"gender\" placeholder=\"Gender\">\n");
      out.write("					<input type=\"number\" name=\"age\" placeholder=\"Age\">\n");
      out.write("					<input type=\"number\" name=\"contactNo\" placeholder=\"ContactNo\">\n");
      out.write("					<input type=\"text\" name=\"address\" placeholder=\"Address\">\n");
      out.write("					<input type=\"email\" name=\"emailid\" placeholder=\"Email\"> \n");
      out.write("					<input type=\"password\" name=\"password\" placeholder=\"Password\">\n");
      out.write("	\n");
      out.write("					<input type=\"submit\" value=\"Sign Up\">\n");
      out.write("				</form>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Footer goes here -->\n");
      out.write("	<br>\n");
      out.write("	<br>\n");
      out.write("	<br>\n");
      out.write("	<br>\n");
      out.write("	<div id=\"footer\">\n");
      out.write("		");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"footer mt-auto py-3 bg-dark\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"text-center\">\n");
      out.write("			<span class=\"text-white\"><i class=\"far fa-copyright\"></i>&nbsp;Copyright\n");
      out.write("				2021&nbsp;|&nbsp;Airline Reservation System&nbsp;|</span> <a\n");
      out.write("				href=\"https://github.com/NirajThagunna\" target=\"_blank\"\n");
      out.write("				rel=\"noopener noreferrer\" style=\"text-decoration: none;\"><i\n");
      out.write("				class=\"fab fa-github\"></i>&nbsp;Github <span style=\"color: white\">|&nbsp;</span></a>\n");
      out.write("			<a href=\"https://www.linkedin.com/in/niraj-thagunna/\" target=\"_blank\"\n");
      out.write("				rel=\"noopener noreferrer\" style=\"text-decoration: none;\"><i\n");
      out.write("				class=\"fab fa-linkedin\"></i>&nbsp;LinkedIn</a>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</footer>");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- JavaScript Code -->\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\">");
      out.write("\n");
      out.write("    $(document).ready(function(){\n");
      out.write("    $('.login-info-box').fadeOut();\n");
      out.write("    $('.login-show').addClass('show-log-panel');\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("$('.login-reg-panel input[type=\"radio\"]').on('change', function() {\n");
      out.write("    if($('#log-login-show').is(':checked')) {\n");
      out.write("        $('.register-info-box').fadeOut(); \n");
      out.write("        $('.login-info-box').fadeIn();\n");
      out.write("        \n");
      out.write("        $('.white-panel').addClass('right-log');\n");
      out.write("        $('.register-show').addClass('show-log-panel');\n");
      out.write("        $('.login-show').removeClass('show-log-panel');\n");
      out.write("        \n");
      out.write("    }\n");
      out.write("    else if($('#log-reg-show').is(':checked')) {\n");
      out.write("        $('.register-info-box').fadeIn();\n");
      out.write("        $('.login-info-box').fadeOut();\n");
      out.write("        \n");
      out.write("        $('.white-panel').removeClass('right-log');\n");
      out.write("        \n");
      out.write("        $('.login-show').addClass('show-log-panel');\n");
      out.write("        $('.register-show').removeClass('show-log-panel');\n");
      out.write("    }\n");
      out.write("});\n");
      out.write("  \n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
